#!/usr/local/bin/bash
#
# calculates degree of overlap between two voxels
#
# outputs the number of voxels overlapped (likely to
# overestimate overlap a bit since some voxels not
# /fully/ covered by both
#
# Matthew Taylor 16-08-2007
# 
# corrects for small translations from created voxel to real scan space
# uses xfm generated by makexfm_voxeloverlap.sh now
# mjt 2007-10-04

studyid=$1
idone=$2
idtwo=$3
BASEDIR=${HOME}/scratch/${studyid}_analysis/structural
TRANSFORM=${BASEDIR}/${idtwo}_vox_to_${idone}_vox.mat

MASKONE=${BASEDIR}/${idone}_voxel.nii.gz
MASKTWO=${BASEDIR}/${idtwo}_voxel.nii.gz

MASKINTERIM=${BASEDIR}/overlap_tmp1.nii.gz
MASKINTERIM2=${BASEDIR}/overlap_tmp2.nii.gz

RESSCAN=${BASEDIR}/empty_struc_2mm.nii.gz
VOXONE=${BASEDIR}/${idone}.voxel
VOXTWO=${BASEDIR}/${idtwo}.voxel
BRAINDIR=${BASEDIR}/brains

# method set to one, gives more accurate method
METHOD=1


if ! test -f ${MASKONE}
then
	makevoxelmask.sh ${VOXONE} ${RESSCAN} ${MASKONE}
fi

if ! test -f ${MASKTWO}
then
	makevoxelmask.sh ${VOXTWO} ${RESSCAN} ${MASKTWO}
fi

if ! test -f ${TRANSFORM}
then
	#flirt -dof 6 -in ${BRAINDIR}/${idtwo}_brain -ref ${BRAINDIR}/${idone}_brain -omat ${TRANSFORM}
	makexfm_voxeloverlap.sh ${studyid} ${idone} ${idtwo}
fi

if test -f ${MASKONE} && test -f ${MASKTWO} && test -f ${TRANSFORM}
then
	#echo files found
	flirt -in ${MASKTWO} -ref ${MASKONE} -applyxfm -init ${TRANSFORM} -out ${MASKINTERIM}
	if test ${METHOD}==1
	then
		COORDS=$(fslstats ${MASKONE} -w |gawk '{print $1,$2,$3,$4,$5,$6}')
		fslroi ${MASKINTERIM} ${MASKINTERIM2} ${COORDS}
		OVERLAP=$(fslstats ${MASKINTERIM2} -m)
		echo ${idone} ${idtwo} ${OVERLAP}
	else
		fslmaths ${MASKINTERIM} -mas ${MASKONE} ${MASKINTERIM2}
		BOTH=`fslstats ${MASKINTERIM2} -V | gawk '{print $1}'`
		VOXSIZE=`fslstats ${MASKONE} -V | gawk '{print $1}'`
		OVERLAP=`echo 100*${BOTH}/${VOXSIZE} | bc`
		echo ${idone} ${idtwo} ${BOTH} ${VOXSIZE} ${OVERLAP}
	fi
	rm -f ${MASKINTERIM}
	rm -f ${MASKINTERIM2}
fi

